DROP SEQUENCE OrderSEQ;
DROP SEQUENCE InvoiceSEQ;
DROP SEQUENCE PONoSEQ;

CREATE SEQUENCE OrderSEQ START WITH 2001 INCREMENT BY 1;

CREATE SEQUENCE InvoiceSEQ START WITH 101 INCREMENT BY 1;

CREATE SEQUENCE PONoSEQ START WITH 21 INCREMENT BY 1;